name: hTreecapitator
version: '${version}'
main: fr.haily.hTreecapitator.HTreecapitator
api-version: '1.21'
authors: [ Haily ]
description: Treecapitator plugin.
website: https://github.com/Haiilyyy
softdepend:
  - Jobs
  - PlaceholderAPI
  - WorldGuard
  - GriefPrevention
commands:
  htreecapitator:
    aliases:
      - htc
    description: hTreecapitator main command.
    usage: /htreecapitator
bstats-id: '${bstatsId}'
faststats-token: '${fastStatsToken}'